# Assignment 1 - Part 1
In this assignment, we will go through basic linear algebra, NumPy, and image manipulation using Python to get everyone on the same page.

One of the aims of this assignment is to get you to start getting comfortable searching for useful library functions online. So in many of the functions you will implement, you will have to look up helper functions.

\

## Instructions
* This notebook contain blocks of code, you are required to complete those blocks(where required)
* You are required to copy this notebook ("copy to drive" above) and complete the code.(DO NOT CHANGE THE NAME OF THE FUNCTIONS)

\
\
Also, I'd like to acknowledge the Stanford CS131. This assignment is highly based on the assignments from that course.

First Let's import some dependencies

In [2]:
# Imports the print function from newer versions of python
from __future__ import print_function

# Setup

# The Random module implements pseudo-random number generators
import random 

# Numpy is the main package for scientific computing with Python. 
# This will be one of our most used libraries in this project
import numpy as np

# The Time library helps us time code runtimes
import time


# Some more magic so that the notebook will reload external python modules;
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

# Part 1: Linear Algebra and NumPy Review
In this section, we will review linear algebra and learn how to use vectors and matrices in python using numpy.

## Part 1.1 (5 points)
First, let's test whether you can define the following matrices and vectors using numpy. Look up `np.array()` for help. In the next code block, define $M$ as a $(4, 3)$ matrix, $a$ as a $(1, 3)$ row vector and $b$ as a $(3, 1)$ column vector:

$$M = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
10 & 11 & 12 \end{bmatrix}
$$

$$a = \begin{bmatrix}
1 & 1 & 0
\end{bmatrix}
$$

$$b = \begin{bmatrix}
-1 \\ 2 \\ 5
\end{bmatrix}  
$$ 

In [3]:
### YOUR CODE HERE
M = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
a = np.array([[1,1,0]])
b = np.array([[-1], [2], [5]])
### END CODE HERE
print("M = \n", M)
print("The size of M is: ", M.shape)
print()
print("a = ", a)
print("The size of a is: ", a.shape)
print()
print("b = ", b)
print("The size of b is: ", b.shape)

M = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
The size of M is:  (4, 3)

a =  [[1 1 0]]
The size of a is:  (1, 3)

b =  [[-1]
 [ 2]
 [ 5]]
The size of b is:  (3, 1)


## Part 1.2 (5 points)
Implement the `dot_product()` method below and check that it returns the correct answer for $a^Tb$.

In [4]:
def dot_product(a, b):
    """Implement dot product between the two vectors: a and b.
    (optional): While you can solve this using for loops, we recommend
    that you look up `np.dot()` online and use that instead.
    Args:
        a: numpy array of shape (x, n)
        b: numpy array of shape (n, x)
    Returns:
        out: numpy array of shape (x, x) (scalar if x = 1)
    """
    out = np.dot(a,b)
    ### YOUR CODE HERE
    pass
    ### END YOUR CODE
    return out

In [5]:
# Now, let's test out this dot product. Your answer should be [[1]].
aDotB = dot_product(a, b)
print(aDotB)

print("The size is: ", aDotB.shape)

[[1]]
The size is:  (1, 1)


## Part 1.3 (5 points)
Implement the `complicated_matrix_function()` method and use it to compute $(ab)Ma^T$

IMPORTANT NOTE: The `complicated_matrix_function()` method expects all inputs to be two dimensional numpy arrays, as opposed to 1-D arrays.  This is an important distinction, because 2-D arrays can be transposed, while 1-D arrays cannot.

To transpose a 2-D array, you can use the syntax `array.T` 

In [9]:
def complicated_matrix_function(M, a, b):
    """Implement (a * b) * (M * a.T).
    (optional): Use the `dot_product(a, b)` function you wrote above
    as a helper function.
    Args:
        M: numpy matrix of shape (x, n).
        a: numpy array of shape (1, n).
        b: numpy array of shape (n, 1).
    Returns:
        out: numpy matrix of shape (x, 1).
    """
    out = (a.dot(b))*(M.dot(a.T))
    ### YOUR CODE HERE
    pass
    ### END YOUR CODE
    return out

In [10]:
# Your answer should be $[[3], [9], [15], [21]]$ of shape(4, 1).
ans = complicated_matrix_function(M, a, b)
print(ans)
print()
print("The size is: ", ans.shape)

[[ 3]
 [ 9]
 [15]
 [21]]

The size is:  (4, 1)


In [8]:
M_2 = np.array(range(4)).reshape((2,2))
a_2 = np.array([[1,1]])
b_2 = np.array([[10, 10]]).T
print(M_2.shape)
print(a_2.shape)
print(b_2.shape)
print()

# Your answer should be $[[20], [100]]$ of shape(2, 1).
ans = complicated_matrix_function(M_2, a_2, b_2)
print(ans)
print()
print("The size is: ", ans.shape)

(2, 2)
(1, 2)
(2, 1)

[[ 20]
 [100]]

The size is:  (2, 1)


## Part 1.4 (10 points) [Optional/Bonus]
Implement `eigen_decomp()` and `get_eigen_values_and_vectors()` methods. In this method, perform eigenvalue decomposition on the following matrix and return the largest k eigen values and corresponding eigen vectors (k is specified in the method calls below).

$$M = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \end{bmatrix}
$$


In [ ]:
def eigen_decomp(M):
    """Implement eigenvalue decomposition.
    (optional): You might find the `np.linalg.eig` function useful.
    Args:
        matrix: numpy matrix of shape (m, n)
    Returns:
        w: numpy array of shape (m, m) such that the column v[:,i] is the eigenvector corresponding to the eigenvalue w[i].
        v: Matrix where every column is an eigenvector.
    """
    w = None
    v = None
    ### YOUR CODE HERE
    pass
    ### END YOUR CODE
    return w, v

In [ ]:
def get_eigen_values_and_vectors(M, k):
    """Return top k eigenvalues and eigenvectors of matrix M. By top k
    here we mean the eigenvalues with the top ABSOLUTE values (lookup
    np.argsort for a hint on how to do so.)
    (optional): Use the `eigen_decomp(M)` function you wrote above
    as a helper function
    Args:
        M: numpy matrix of shape (m, m).
        k: number of eigen values and respective vectors to return.
    Returns:
        eigenvalues: list of length k containing the top k eigenvalues
        eigenvectors: list of length k containing the top k eigenvectors
            of shape (m,)
    """
    eigenvalues = []
    eigenvectors = []
    ### YOUR CODE HERE
    pass
    ### END YOUR CODE
    return eigenvalues, eigenvectors

In [ ]:
# Let's define M.
M = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Now let's grab the first eigenvalue and first eigenvector.
# You should get back a single eigenvalue and a single eigenvector.
val, vec = get_eigen_values_and_vectors(M[:,:3], 1)
print("First eigenvalue =", val[0])
print()
print("First eigenvector =", vec[0])
print()
assert len(vec) == 1

# Now, let's get the first two eigenvalues and eigenvectors.
# You should get back a list of two eigenvalues and a list of two eigenvector arrays.
val, vec = get_eigen_values_and_vectors(M[:,:3], 2)
print("Eigenvalues =", val)
print()
print("Eigenvectors =", vec)
assert len(vec) == 2

## Part 1.5 (10 points)
In this section, you'll implement a gaussian elimination.

The algorithm to to reduce a matrix to rref using gaussian elimination contains 2 parts, First reducing the matrix to partial reduced form, then back substituting to calculate the rref. First algorithm can be summed up as:
1. Partial pivoting: Find the kth pivot by swapping rows, to move the entry with the largest absolute value to the pivot position. This imparts computational stability to the algorithm.
2. For each row below the pivot, calculate the factor f which makes the kth entry zero, and for every element in the row subtract the fth multiple of the corresponding element in the kth row.
3. Repeat above steps for each unknown. We will be left with a partial r.e.f. matrix.

$$\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \end{bmatrix}
=>
\begin{bmatrix}
7 & 8 & 9 \\
4 & 5 & 6 \\
1 & 2 & 3 \end{bmatrix}
=>
\begin{bmatrix}
7 & 8 & 9 \\
0 & 0.42 & 0.85 \\
0 & 0.85 & 1.71 \end{bmatrix}
=>
\begin{bmatrix}
7 & 8 & 9 \\
0 & 0.85 & 1.71 \\
0 & 0.45 & 0.85 \end{bmatrix}
=>
\begin{bmatrix}
7 & 8 & 9 \\
0 & 0.42 & 0.85 \\
0 & 0 & -0.05 \end{bmatrix}
$$
Second algorithm:
1. Take a pivot from the last row.
2. For each row above the pivot, calculate the factor f which makes the kth entry zero, and for every element in the row subtract the fth multiple of the corresponding element in the kth row
3. Repeat the above step untill the matrix is in rref
$$\begin{bmatrix}
7 & 8 & 0 \\
0 & 0.42 & 0 \\
0 & 0 & -0.05 \end{bmatrix}
=>
\begin{bmatrix}
7 & 0 & 0 \\
0 & 0.42 & 0 \\
0 & 0 & -0.05 \end{bmatrix}
$$

Steps for implementation:
1. Complete the function `swap_rows()`
2. Complete the function `apply_row()`
3. Complete `forward()` and `backward()`
4. Finally implement `rref()` using the `forward()` and `backward()`

Note: You can skip this part if you want.

In [ ]:
def swap_rows(M):
    """Implement row swapping to make the largest element in the pivotial column to be the first row.
    Args:
        matrix: numpy matrix of shape (m, n)
    Returns:
        Ms: matrix with swapped row
    """
    a = np.array([[1,2,3], [4,5,6], [7,8,9]])
    b = a[[0,2]] = a[[2,0]]
    out = b
    ### YOUR CODE HERE
    pass
    ### END YOUR CODE
    return out

In [ ]:
def apply_rows(M):
    """For each row below the pivot, calculate the factor f which makes the kth
    entry zero, and for every element in the row subtract the fth multiple of the
    corresponding element in the kth row.
    Args:
        matrix: numpy matrix of shape (m, n)
    Returns:
        Ms: matrix with all other entries of the pivotal col zero
    """
    out = None
    ### YOUR CODE HERE
    pass
    ### END YOUR CODE
    return out

In [ ]:
def forward(M):
    """Return a partial ref using the algo described above
    Args:
        M: numpy matrix of shape (m, n).
    Returns:
        Ms: ref of M
    """
    out = None
    ### YOUR CODE HERE
    pass
    ### END YOUR CODE
    return out

In [ ]:
def backward(M):
    """Return a rref using the algo described above
    Args:
        M: numpy matrix of shape (m, n).
    Returns:
        Ms: rref of M
    """
    out = None
    ### YOUR CODE HERE
    pass
    ### END YOUR CODE
    return out

In [ ]:
def rref(M):
    """Return a rref using the algo descrbed above
    Args:
        M: numpy matrix of shape (m, n).
    Returns:
        Ms: ref of M
    """
    out = None
    ### YOUR CODE HERE
    pass
    ### END YOUR CODE
    return out

In [ ]:
# Let's define M.
M = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Now let's calculate it's rref.
# Note that your code may be evaluated on other test cases as well
Mrref = rref(M)
print(Mrref)

## Part 1.6 (10 points)

To wrap up our overview of NumPy, let's implement something fun &mdash; a helper function for computing the Euclidean distance between two $n$-dimensional points!

In the 2-dimensional case, computing the Euclidean distance reduces to solving the Pythagorean theorem $c = \sqrt{a^2 + b^2}$. where, given two points $(x_1, y_1)$ and $(x_2, y_2)$, $a = x_1 - x_2$ and $b = y_1 - y_2$.


More generally, given two $n$-dimensional vectors, the Euclidean distance can be computed by:

1. Performing an elementwise subtraction between the two vectors, to get $n$ difference values.
2. Squaring each of the $n$ difference values, and summing the squares.
4. Taking the square root of our sum.

Alternatively, the Euclidean distance between length-$n$ vectors $u$ and $v$ can be written as:

$
\quad\textbf{distance}(u, v) = \sqrt{\sum_{i=1}^n (u_i - v_i)^2}
$


Try implementing this function: first using native Python with a `for` loop in the `euclidean_distance_native()` function, then in NumPy **without any loops** in the `euclidean_distance_numpy()` function.
We've added some `assert`  statements here to help you check functionality (if it prints nothing, then your implementation is correct)!

In [ ]:
def euclidean_distance_native(u, v):
    """Computes the Euclidean distance between two vectors, represented as Python
    lists.
    Args:
        u (List[float]): A vector, represented as a list of floats.
        v (List[float]): A vector, represented as a list of floats.
    Returns:
        float: Euclidean distance between `u` and `v`.
    """
    # First, run some checks:
    assert isinstance(u, list)
    assert isinstance(v, list)
    assert len(u) == len(v)

    # Compute the distance!
    # Notes:
    #  1) Try breaking this problem down: first, we want to get
    #     the difference between corresponding elements in our
    #     input arrays. Then, we want to square these differences.
    #     Finally, we want to sum the squares and square root the
    #     sum.
    j=0
    diff=[]
    sum=0
    for x in u :
      diff.append((x-v[j])**2)
      j +=1
    for y in diff :
      sum=sum+y
    dist = sum**0.5
    out = dist
    ### YOUR CODE HERE
    pass
    ### END YOUR CODE
    return out

In [ ]:
def euclidean_distance_numpy(u, v):
    """Computes the Euclidean distance between two vectors, represented as NumPy
    arrays.
    Args:
        u (np.ndarray): A vector, represented as a NumPy array.
        v (np.ndarray): A vector, represented as a NumPy array.
    Returns:
        float: Euclidean distance between `u` and `v`.
    """
    # First, run some checks:
    assert isinstance(u, np.ndarray)
    assert isinstance(v, np.ndarray)
    assert u.shape == v.shape

    # Compute the distance!
    # Note:
    #  1) You shouldn't need any loops
    #  2) Some functions you can Google that might be useful:
    #         np.sqrt(), np.sum()
    #  3) Try breaking this problem down: first, we want to get
    #     the difference between corresponding elements in our
    #     input arrays. Then, we want to square these differences.
    #     Finally, we want to sum the squares and square root the
    #     sum.
    p= np.subtract(u,v)
    q= np.square(p)
    r= np.sum(q)
    dist= r**0.5

    ### YOUR CODE HERE
    pass
    ### END YOUR CODE
    return dist

In [ ]:
## Testing native Python function
assert euclidean_distance_native([7.0], [6.0]) == 1.0
assert euclidean_distance_native([7.0, 0.0], [3.0, 3.0]) == 5.0
assert euclidean_distance_native([7.0, 0.0, 0.0], [3.0, 0.0, 3.0]) == 5.0

In [ ]:
## Testing NumPy function
assert euclidean_distance_numpy(
    np.array([7.0]),
    np.array([6.0])
) == 1.0
assert euclidean_distance_numpy(
    np.array([7.0, 0.0]),
    np.array([3.0, 3.0])
) == 5.0
assert euclidean_distance_numpy(
    np.array([7.0, 0.0, 0.0]),
    np.array([3.0, 0.0, 3.0])
) == 5.0

In [ ]:
n = 1000

# Create some length-n lists and/or n-dimensional arrays
a = [0.0] * n
b = [10.0] * n
a_array = np.array(a)
b_array = np.array(b)

# Compute runtime for native implementation
start_time = time.time()
for i in range(10000):
    euclidean_distance_native(a, b)
print("Native:", (time.time() - start_time), "seconds")

# Compute runtime for numpy implementation
# Start by grabbing the current time in seconds
start_time = time.time()
for i in range(10000):
    euclidean_distance_numpy(a_array, b_array)
print("NumPy:", (time.time() - start_time), "seconds")

Native: 2.398136615753174 seconds
NumPy: 0.09127545356750488 seconds


Next, let's take a look at how these two implementations compare in terms of runtime:

As you can see, doing vectorized calculations (i.e. no for loops) with NumPy results in significantly faster computations! 

Congrats You've come to the end of this notebook. If you solved everything above, impressive. If not, you might need to read/think a bit more. You can always ask doubts. Also, Note that you should submit it even if you cannot solve everything. We might evaluate these using a script later.